### ISSUE TITLE
tomcat_exporter doesn't work

### ISSUE THREAD

**Issue by rusafan** [nlighten/tomcat_exporter#30]
tomcat_exporter doesn't work
Can't understand why?

We use:
Apache Tomcat/8.5.57
java version "1.8.0_261"

files below added to Tomcat8.5\lib\
simpleclient_servlet-0.12.0.jar
simpleclient_hotspot-0.12.0.jar
simpleclient_common-0.12.0.jar
simpleclient-0.12.0.jar
tomcat_exporter_client-0.0.14.jar -> renamed to metrics.jar

from log where 'metrics':
23-Sep-2021 10:31:37.785 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\BMC\Tomcat8.5\webapps\metrics.war]
23-Sep-2021 10:31:37.832 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
	org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/metrics]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: java.lang.NoClassDefFoundError: io/prometheus/client/servlet/common/exporter/ServletConfigurationException
		at java.lang.Class.getDeclaredFields0(Native Method)
		at java.lang.Class.privateGetDeclaredFields(Unknown Source)
		at java.lang.Class.getDeclaredFields(Unknown Source)
		at org.apache.catalina.util.Introspection.getDeclaredFields(Introspection.java:110)
		at org.apache.catalina.startup.WebAnnotationSet.loadFieldsAnnotation(WebAnnotationSet.java:269)
		at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:137)
		at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:69)
		at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:328)
		at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:782)
		at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5053)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 10 more
	Caused by: java.lang.ClassNotFoundException: io.prometheus.client.servlet.common.exporter.ServletConfigurationException
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 23 more
23-Sep-2021 10:31:37.832 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [C:\BMC\Tomcat8.5\webapps\metrics.war]
	java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/metrics]]
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:747)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)

**Comment by nlighten** [comment]
Please test with version 0.9.0 of the prometheus jars. If this solves your problem I will create a new build to match the version 0.12.0 that you used.

**Comment by rusafan** [comment]
Thanks a lot. 0.9.0 works 👍
